version: "2"

services:
  gitlabrunner:
    build: .
    # image: gitlab/gitlab-runner:latest
    container_name: "${PROJECT_NAME}"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./config:/etc/gitlab-runner:cached
    labels:
      - 'traefik.backend=gitlabrunner'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:gitlab.${PROJECT_BASE_URL}'

